s3_bucket: mnemosyne-team-bucket
exp_name: cifar10_graphnet_GraSP_prune_ratio_98
trial_id: 0
s3_path: SamuelS/GraSP/data/${exp_name}/trial_${trial_id}/${now:%Y-%m-%d_%H-%M-%S}
network: graphnet
depth: 20
dataset: cifar10
batch_size: 128
epoch: 160
learning_rate: 0.1
weight_decay: 1e-4
exception: -1
iterations: 1
normalize: False
target_op_ratio: 0.75
target_weight_ratio: 0.90
pruner: GraSP
pruner_file: GraSP
samples_per_class: 10