project_name: GraSP
project_version: 0.0.1
defaults:
  - dataset: cifar10
  - network: graphnet
  - logger: local

op_pruner:
  type: grasp_mag
  target_percent: 75
  num_iter: 1
  samples_per_class: 10

weight_pruner:
  type: grasp_mag
  target_percent: 0
  samples_per_class: 10

optimizer:
  learning_rate: 0.1
  weight_decay: 1e-4

num_train_epochs: 160
grasp_logit_scale: 1

trial_id: 0
seed:
exception: -1
debug: False
view_graphs: False

# Directories for loading and storing data
data_dir: data
exp_name: ${network.type}${network.params.depth}_${op_pruner.type}${op_pruner.target_percent}_${weight_pruner.type}${weight_pruner.target_percent}_${dataset.name}
log_dir: ${data_dir}/experiments/${exp_name}/trial_${trial_id}/${now:%Y-%m-%d_%H-%M-%S}
checkpoint_dir: ${log_dir}/checkpoints

s3_bucket: mnemosyne-team-bucket
s3_path: SamuelS/${project_name}/${log_dir}

hydra:
  run:
    dir: ./${log_dir}

# AWS BatchExperiments command-line overrides
hostfile:
num_gpus:
num_cpus: