project_name: GraSP
defaults:
  - dataset: cifar10
  - network: graphnet
  - logger: local

op_pruner:
  type: grasp
  target_ratio: 0.75
  num_iter: 1
  samples_per_class: 10

weight_pruner:
  type: grasp
  target_ratio: 0.
  samples_per_class: 10

optimizer:
  learning_rate: 0.1
  weight_decay: 1e-4

num_train_epochs: 160

trial_id: 0
seed:
exception: -1
debug: False
view_graphs: False

# Directories for loading and storing data
data_dir: data
exp_name: test_experiment
log_dir: ${data_dir}/experiments/${exp_name}/trial_${trial_id}/${now:%Y-%m-%d_%H-%M-%S}
checkpoint_dir: ${log_dir}/checkpoints

s3_bucket: mnemosyne-team-bucket
s3_path: SamuelS/GraSP/${log_dir}

hydra:
  run:
    dir: ./${log_dir}

# AWS BatchExperiments command-line overrides
hostfile:
num_gpus:
num_cpus: